POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Muhammad Rizky Aditiya Saputra",
  "email": "aditiyas0108@gmail.com",
  "password": "1Lupa2ingat_"
}

###

POST http://localhost/api/auth/login
Content-Type: application/json

{
    "email" : "aditiyas0108@gmail.com",
    "password" : "1Lupa2ingat_"
}